# Generated by Django 5.0.7 on 2024-07-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pedido_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
